# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 23:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomedoDepartamento', models.CharField(max_length=128)),
                ('local', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=128)),
                ('datadenascimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnh', models.CharField(max_length=128)),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transporte_app.Funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataH_solicitacao', models.DateTimeField(blank=True, null=True)),
                ('origem', models.CharField(max_length=128)),
                ('destino', models.CharField(max_length=128)),
                ('Funcionarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transporte_app.Funcionario')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transporte_app.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomedoVeiculo', models.CharField(max_length=128)),
                ('anodoveiculo', models.CharField(max_length=128)),
                ('placa', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='atender',
            name='Motorista',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='transporte_app.Motorista'),
        ),
        migrations.AddField(
            model_name='atender',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atender',
            name='veiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transporte_app.Veiculo'),
        ),
    ]
