# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte_app', '0002_atender_solicitacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atender',
            old_name='Motorista',
            new_name='motorista',
        ),
    ]
